### ISSUE TITLE
Doesn't work on a self-hosted runners behind a proxy server

### ISSUE THREAD

**Issue by tanmayghosh2507** [microsoft/action-publish-symbols#12]
Related to #4

**Comment by tanmayghosh2507** [comment]
Fixed the issue with #24 .

**Comment by sokunna** [comment]
@tanmayghosh2507 I'm still seeing the same issue when running on a self-hosted linux agent behind a proxy server. 
<img width="965" alt="image" src="https://user-images.githubusercontent.com/30151191/176808730-02f48a83-6d4a-4acd-9793-2d21fc020849.png">

**Comment by sokunna** [comment]
@tanmayghosh2507 the problem is solved when running on a github linux agent. But the self-hosted agent behind the proxy is still an issue.

**Comment by sokunna** [comment]
@tanmayghosh2507 here's the log 
<img width="667" alt="image" src="https://user-images.githubusercontent.com/30151191/176948503-004caa55-2dfd-41b8-b2b1-058530d589c3.png">

**Comment by tanmayghosh2507** [comment]
Hi @sokunna Seems like a network issue while connecting to our server to download the symbol executable from your end. Can you check on your end if you get the similar issue while trying to connect to an external server from your hosted agent, if possible?
